### ISSUE TITLE
V3.0 single table inheritance fails

### ISSUE THREAD

**Issue by danlewis** [wvanbergen/scoped_search#112]
I have the following query on a model with single table inheritance (EmailAssignment is a subclass of MessageAssignment)
EmailAssignment.search_for(nil).page(1)

Version 2.7.1 worked fine generating the following query:
EmailAssignment Load (0.6ms)  SELECT  "message_assignments".\* FROM "message_assignments"  WHERE "message_assignments"."type" IN ('EmailAssignment')  ORDER BY id DESC LIMIT 24 OFFSET 0

Version 3.0 however generates the following query which returns unwanted results.
MessageAssignment Load (0.7ms)  SELECT  "message_assignments".\* FROM "message_assignments"   ORDER BY id DESC LIMIT 24 OFFSET 0

**Comment by wvanbergen** [comment]
We never officially supported single table inheritance; i.e. there's no tests covering this functionality. Apparently it worked by luck because ActiveRecord's magic was appending the WHERE clause to our query.

I am not against supporting this, but it's unlikely I will have time to work on this anytime soon.
