### ISSUE TITLE
Getting undefined method error on has-many through search

### ISSUE THREAD

**Issue by johnpmitsch** [wvanbergen/scoped_search#131]
related to http://projects.theforeman.org/issues/10551

Searching this particular has-many through relationship will cause raise an error. Autocomplete works fine.

```ruby                                                  
has_many :environments, :through      => :content_view_environments,
                        :class_name   => "Katello::KTEnvironment",
                        :inverse_of   => :content_view_versions,
                        :after_remove => :remove_environment


scoped_search :in => :environments, :on => :name, :rename => :environment, :complete_value => true
```

server output
```
2015-05-27 11:23:05 [I] Completed 500 Internal Server Error in 16.6ms (Views: 0.3ms | ActiveRecord: 1.2ms)
2015-05-27 11:23:05 [D] With body: {"displayMessage":"undefined method `klass' for nil:NilClass","errors":["undefined method `klass' for nil:NilClass"]}
```

**Comment by johnpmitsch** [comment]
@jlsherrill

**Comment by jlsherrill** [comment]
I investigated this a tad bit (when i was investigating the issue with @johnpmitsch), the issue is here:

https://github.com/wvanbergen/scoped_search/blob/master/lib/scoped_search/query_builder.rb#L260

reflection_by_name() is being called and passed a table name, not the name of an association.  Since we are using this within an isolated engine and are properly namespacing all of our models, the table name here is katello_content_view_environments, but the association name on the end object is simply 'content_view_environments'.

You can reproduce this in the test with this simple change:

```
diff --git a/spec/integration/relation_querying_spec.rb b/spec/integration/relation_querying_spec.rb
index 53638c6..01149e4 100644
--- a/spec/integration/relation_querying_spec.rb
+++ b/spec/integration/relation_querying_spec.rb
@@ -255,7 +255,7 @@ ScopedSearch::RSpec::Database.test_databases.each do |db|
 
         # The related classes
         class Mar < ActiveRecord::Base; belongs_to :baz; belongs_to :koo; end
-        class Baz < ActiveRecord::Base; has_many :mars; end
+        class Baz < ActiveRecord::Base; has_many :other_mars, :class_name => "Mar", :foreign_key => :b
 
         # The class on which to call search_for
         class Koo < ActiveRecord::Base
```

**Comment by johnpmitsch** [comment]
@wvanbergen @domcleal thanks! any idea when this will be released so we can start using it in katello?

**Comment by wvanbergen** [comment]
Version 3.2.2 has been released.

**Comment by johnpmitsch** [comment]
@wvanbergen :+1:
