### ISSUE TITLE
Searching for future dates by relative days

### ISSUE THREAD

**Issue by thomasmckay** [wvanbergen/scoped_search#162]
Today is: 2017-03-06 (day 65)
Database record is: 2017-06-19 (day 170)

Search success: expires < "172 days"
Search zero results: expires < "171 days"
Search zero results: expires < "Today + 175 days"

As a user, my expectation is that date searches are relative to today. Trying "Today +" syntax also yields zero results.

**Comment by thomasmckay** [comment]
scoped_search 4.0.0

**Comment by domcleal** [comment]
If `expires` is a date/time field, then the syntax you are using isn't correct, it should be "172 days ago", not "172 days".

See https://github.com/wvanbergen/scoped_search/wiki/Query-language#temporal-comparisons

Otherwise please include more precise information about the field definition, the database field type and the generated SQL query.

**Comment by thomasmckay** [comment]
These are future dates being searched for, not in the past. What is the syntax for that?

**Comment by domcleal** [comment]
There is no relative syntax (certainly not just "X days"), use absolute dates or add support.

**Comment by thomasmckay** [comment]
Consider this an RFE then.
