### ISSUE TITLE
postgres has array or json fields too

### ISSUE THREAD

**Issue by geekdreamzz** [wvanbergen/scoped_search#99]
would be nice if we could query search those columns too with this gem. not really an issue more like proposal but i'm getting an error searching on tags column since its stored as an array in postgres, but it looks like this gem is just for querying strings?

**Comment by stevelacey** [comment]
@wvanbergen I need this and am up for trying to add it in if you have any guidance as to how it might be doable

**Comment by wvanbergen** [comment]
- The different SQL expression snippets that compose the SQL queries are generated here: https://github.com/wvanbergen/scoped_search/blob/master/lib/scoped_search/query_builder.rb#L209-L247
- You may also want to expose some additional information about the field in the field definition: https://github.com/wvanbergen/scoped_search/blob/master/lib/scoped_search/definition.rb

**Comment by stevelacey** [comment]
I managed to get most of the way there using the [external search methods](https://github.com/wvanbergen/scoped_search/wiki/Usage#external-search-methods) functionality:

```rb
  scoped_search on: :custom, :ext_method => :find_by_custom

  def self.find_by_custom(key, operator, value)
    if '.'.in? key.to_s
      segments = key.to_s.split('.')
      key = sanitize_sql_array([
        '(' + segments.shift().gsub(/[^\w]/, '') + '->?' * (segments.length - 1) + '->>?' + ')',
        *segments
      ])
    end

    if value.downcase == 'null'
      value = nil

      if operator == '='
        operator = 'IS'
      elsif operator == '<>'
        operator = 'IS NOT'
      end
    end

    { :conditions => sanitize_sql_for_conditions(["#{key} #{operator} ?", value]) }
  end
```

Simply leverages the way that everything after the first dot in a field name appears to be discounted (not sure why that is?), but means that I can just map a ext_method to my `custom` JSON field, great! – then I accept dot notation in order to build out a reference to a property in a Postgres JSON field – with hacked in support for `null` queries since `null?` and `set?` hit the core methods and throw a wobbly (and have weird syntax my users will never guess anyway).

Whilst this is a bit of a hacky solve, there are only two main caveats that are bothering me (although not too much): non-standard null handling, and inability to support `like`/`unlike` given that operation exceptions are thrown further up since my `custom` field is not textual.

**Comment by wvanbergen** [comment]
This is cool. I am very open to add some helper functions that would make custom behavior like this easier to implement.

**Comment by stevelacey** [comment]
I am generally happy with my implementation, the only weaknesses are the null handling, which I think could be better across the gem generally – it's a bit obscure; and lack of handling of more complex data structures in my implementation, e.g. JSON arrays.

**Comment by wvanbergen** [comment]
I am open for suggestions, but that would be something for a next major version.

**Comment by collimarco** [comment]
+1 for this feature

We have various array fields in PostgreSQL and it would be useful to include those fields in the search.

Does anyone have a modified fork or pull request for that? @stevelacey
